# Generated by Django 5.2.6 on 2025-09-21 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_pago', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_comunes', to='maintenance.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='TarifaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_final', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='reservations.areacomun')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_url', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('EnUso', 'En Uso')], default='Disponible', max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('total', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservations.areacomun')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='accounts.persona')),
            ],
            options={
                'unique_together': {('area', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
