# Generated by Django 5.2.6 on 2025-09-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_hogar', models.CharField(choices=[('Titular', 'Titular'), ('Conyuge', 'Cónyuge'), ('Hijo', 'Hijo'), ('Inquilino', 'Inquilino')], max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='accounts.persona')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupantes', to='maintenance.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento')], max_length=20)),
                ('porcentaje', models.FloatField(help_text='Porcentaje de copropiedad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='accounts.persona')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='maintenance.unidad')),
            ],
        ),
    ]
