# Generated by Django 5.2.6 on 2025-09-21 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('nombre', models.CharField(max_length=50)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='maintenance.condominio')),
            ],
            options={
                'unique_together': {('nombre', 'condominio')},
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='maintenance.condominio')),
            ],
            options={
                'unique_together': {('nombre', 'condominio')},
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('codigo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('mantenimiento', models.FloatField(default=0.0)),
                ('numero', models.IntegerField()),
                ('piso', models.CharField(max_length=20)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='maintenance.bloque')),
            ],
            options={
                'unique_together': {('codigo', 'bloque')},
            },
        ),
    ]
