# Generated by Django 5.2.6 on 2025-09-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('costo_estimado', models.FloatField(default=0.0)),
                ('costo_real', models.FloatField(default=0.0)),
                ('estado', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('EnProceso', 'En Proceso'), ('Completo', 'Completo')], default='Solicitado', max_length=20)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10)),
                ('tipo', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Correctivo', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='maintenance.activo')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='accounts.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Inicio', 'Inicio'), ('EnProceso', 'En Proceso'), ('Completo', 'Completo')], default='Inicio', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='accounts.personal')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='maintenance.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.personal')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='maintenance.tarea')),
            ],
        ),
    ]
